version: '3.5'

services:
  app-core:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/var/www
      - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    depends_on:
      - mysql
    user: "www"

  webserver:
    image: nginx:alpine
    restart: unless-stopped
    tty: true
    ports:
      - "${APP_PORT}:80"
    volumes:
      - ./:/var/www
      - ./docker/nginx/conf.d/:/etc/nginx/conf.d/

  mysql:
    image: mysql:8.4.0
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    restart: unless-stopped
    volumes:
      - mysql_data_core:/var/lib/mysql
      - ./docker/mysql/my.cnf:/etc/mysql/my.cnf

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "${APP_PORT_PHPMYADMIN}:80"
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=mysql
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
      - PMA_PORT=${DB_PORT}

volumes:
  mysql_data_core:
